/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/cYBjJplxnAN
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Toggle } from "@/components/ui/toggle"

export function Toggles() {
  return (
    <>
      <div className="flex items-center gap-4">
        <div className="flex items-center gap-2">
          <Toggle aria-label="Toggle move shapes">
            <MoveIcon className="h-5 w-5" />
            Move
          </Toggle>
        </div>
        <div className="flex items-center gap-2">
          <Toggle aria-label="Toggle draw rectangles">
            <RectangleVerticalIcon className="h-5 w-5" />
            Draw
          </Toggle>
        </div>
      </div>
      <div className="grid grid-cols-3 gap-4 mt-4">
        <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4 flex items-center justify-center">
          <div className="bg-gray-900 dark:bg-gray-50 w-10 h-10 rounded-md" />
        </div>
        <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4 flex items-center justify-center">
          <div className="bg-gray-900 dark:bg-gray-50 w-10 h-10 rounded-full" />
        </div>
        <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4 flex items-center justify-center">
          <div className="bg-gray-900 dark:bg-gray-50 w-20 h-10 rounded-md" />
        </div>
      </div>
    </>
  )
}

function MoveIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="5 9 2 12 5 15" />
      <polyline points="9 5 12 2 15 5" />
      <polyline points="15 19 12 22 9 19" />
      <polyline points="19 9 22 12 19 15" />
      <line x1="2" x2="22" y1="12" y2="12" />
      <line x1="12" x2="12" y1="2" y2="22" />
    </svg>
  )
}


function RectangleVerticalIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="12" height="20" x="6" y="2" rx="2" />
    </svg>
  )
}
